### ISSUE TITLE
fix drag release bug (lower priority)

### ISSUE THREAD

**Issue by magland** [flatironinstitute/labbox-ephys#121]
In electrode geometry view... drag to select and then release outside the widget. The selection does not end until after the mouse re-enters the widget area.

Not a big deal, and not sure how difficult this will be to fix. But if it easy...

**Comment by jsoules** [comment]
I think the precise condition for ending the drag select is that there is a mouse movement event in the canvas area while the button is not pressed... if you move outside the canvas area, release the mouse button, then hold it again before re-entering, I believe the drag continues with the same anchor.

Anyway, I've been thinking about this one and I'm not really sure what the best approach is here. One possible behavior is to just end the drag if the mouse moves outside the canvas, and we could achieve that with an onmouseleave listener. However, this can be both an annoyance when trying to drag up against the edge of the canvas area (requiring needlessly slow/precise mouse movements to avoid losing the selection), and an accessibility issue more generally (for users with hand tremors, etc).

While I guess we could track things and reinstate the drag & undo the state change from ending it if there's a mouseenter with the button held down... but I think the real bug in the current version is that a mouse release outside the canvas does not actually end the dragging. I'm not sure how to resolve this--I don't think we're picking up mouseup events from outside the Widget's area, because if we were we might not be having this problem in the first place, but I need to sift through that a little more and see.

**Comment by jsoules** [comment]
How about this for the behavior: add a flag that governs whether the selection is active or asleep. onmouseleave, set this flag to sleep. While the drag region is asleep, the layer knows not to render it, however the anchor will not be cleared and the drag-selection events won't fire (as they would if you ended the select by going outside the area).
onmouseenter, we check the button state. If the button is held, we restore the sleeping drag region in a still-dragging state; if it was released, we ?? -- either finalize the last region or, if this is too 'spooky-things-happen-with-time-delay', we can just quietly clear the drag region.

Does that sound good?

**Comment by magland** [comment]
I'm not sure. I think we should discuss in person. The main thing to try to achieve is that if the user drags a rectangle, goes outside of the widget, and then releases the mouse button, they expect the drag-release functionality to kick in. Not sure if this is easy though. There must be a way, because sometimes users need to drag things to other parts of the page.
