### ISSUE TITLE
handle case where all electrodes have same coordinate, eg (0, 0)

### ISSUE THREAD

**Issue by magland** [flatironinstitute/labbox-ephys#292]

**Comment by jsoules** [comment]
This was prompted by the case of tetrodes where the exact location isn't known, which had been marked as all 0s, and which we'd talked about sending to a small diamond shape or something.

That solves this specific case, but we should make sure that it's an acceptable default for other labs. I'm also concerned that it would not generalize to other electrode counts; we could do some kind of rule (map them to the corners of a regular n-gon centered at the origin; assume a straight line; etc...) but I suspect that the potential for misleading downstream analysis could grow rapidly as the number of probes increases, if we make arbitrary assignments that imply a certain structure in the electrode neighborhoods.

Somewhat related: we probably ought to check for the presence of any pair of electrodes located at the same spot, even if it's not all the electrodes on the probe; it's probably still corrupted electrode geometry data that might need to be fixed by user intervention in the data file.
