### ISSUE TITLE
Compatibility with Jupyter lab 3.0

### ISSUE THREAD

**Issue by khl02007** [flatironinstitute/labbox-ephys#336]
Jupyter lab widget seems to not get installed in Jupyter lab 3.0

```shell
(nwb_datajoint) kyu@virga-00:~/repos/labbox-ephys$ jupyter labextension install jupyterlab/labbox_ephys_widgets_jp
An error occured.
ValueError:
"labbox_ephys_widgets_jp@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLabExtension        Package
>=17.0.1 <18.0.016.9.0           react
>=17.0.1 <18.0.016.9.0           react-dom
See the log file for details:  /tmp/jupyterlab-debug-5iz6zds2.log
```

**Comment by magland** [comment]
Thanks for the report. It seems that since the different jupyterlab versions use different versions of react, we may need to maintain different versions of the extension (since we don't necessarily want to require version 3 of jupyterlab). We'll need to think about the right way forward.
@khl02007 - are you able to stick with jupyterlab 2 for the time being?

Tagging: @jsoules
